[[constraint]]
  branch = "master"
  name = "github.com/shomali11/slacker"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/evandroflores/pong"
  go-version = "1.12"
  ensure = "false"
  install = [ "./..." ]